const students = [
    {
    id:1,
    Student:'Schuyler,Shawdforth',
    email:'tblaguese1@gmail.com',
    IP1: 29,
    IP2: 17,
    IP3: 19,
    IP4: 27,
    Attendance: 100,
    Firstrecommendation:'Yes',
    reason1:'',
    Finalrecommendation:'yes',
    reason2:'',
    is_receiver:true,
    },
    {
    id:2,
    Student:'Renato,Deverille',
    email:'rdeverille7@canalblog.com',
    IP1: 21,
    IP2: 14,
    IP3: 14,
    IP4: 16,
    Attendance: 100,
    Firstrecommendation:'No',
    reason1:'IP quality and completion',
    Finalrecommendation:'No',
    reason2:'IP quality and completion',
    is_receiver:false,
    },
    {
    id:3,
    Student:'Carey, Locker',
    email:'clocker3@chron.com',
    IP1: 29,
    IP2: 20,
    IP3: 20,
    IP4: 25,
    Attendance: 100,
    Firstrecommendation:'Yes',
    reason1:'',
    Finalrecommendation:'Yes',
    reason2:'',
    is_receiver:true,
    },
    {
    id:4,
    Student:'Brnaby,Clitheroe',
    email:'bclitheroe5@live.com',
    IP1: 23,
    IP2: 19,
    IP3: 15,
    IP4: 18,
    Attendance: 99,
    Firstrecommendation:'No',
    reason1:'IP quality and completion',
    Finalrecommendation:'No',
    reason2:'IP quality and completion',
    is_receiver:true,
    },
    {
    id:5,
    Student:'Leland, Clohessy',
    email:'Iclohessy4@ow.ly',
    IP1: 23,
    IP2: 16,
    IP3: 17,
    IP4: 23,
    Attendance: 98,
    Firstrecommendation:'Yes',
    reason1:'',
    Finalrecommendation:'Yes',
    reason2:'',
    is_receiver:true,
    },
    {
    id:6,
    Student:'Any,Gillon',
    email:'agillon1@nationalgeographic.com.com',
    IP1: 31,
    IP2: 18,
    IP3: 17,
    IP4: 24,
    Attendance: 94,
    Firstrecommendation:'Yes',
    reason1:'',
    Finalrecommendation:'Yes',
    reason2:'',
    is_receiver:true,
    },
    {
    id:7,
    Student:'Celka,Wellbelove',
    email:'cwellbelove9@time.com.com',
    IP1: 27,
    IP2: 12,
    IP3: 15,
    IP4: 21,
    Attendance: 100,
    Firstrecommendation:'No',
    reason1:'IP quality and completion',
    Finalrecommendation:'No',
    reason2:'IP quality and completion',
    is_receiver:true,
    },
];
module.exports = students;